global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: governance-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - governance-api:8000

  - job_name: opa
    metrics_path: /metrics
    static_configs:
      - targets:
          - opa:8181

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
